name: PROD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: npm install
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          source-directory: dist
          access-token: ${{ secrets.GITHUB_TOKEN }}
          build-command: npm run build
